### PR TITLE
Fix `build_mock_url()` for requests with multipart body with string and raw values

### LINKED ISSUE #39: Requests with multipart body containing character values fail
Character values should also be accepted (see the last example in https://httr2.r-lib.org/reference/req_body.html) but they fail in httptest2:

``` r
library(httr2)
library(httptest2)

path <- tempfile()
writeLines(letters[1:3], path)

req <- request(example_url()) |>
  req_url_path("/post") |>
  req_body_multipart(file = curl::form_file(path), char = "some text", form = curl::form_data("data"))
# req_dry_run(req)
capture_requests(req_perform(req))
#> Error in x$value: $ operator is invalid for atomic vectors
```

It works removing the `char = "some text"` part.

### PR DESCRIPTION
**Pull request by jmaspons**
FIX #39

### CODE REVIEW

File: R/build-mock-url.R [hunk 1]
```diff
@@ -79,9 +79,11 @@ get_string_request_body <- function(req) {
         if (inherits(x, "form_file")) {
           # hash the file contents
           paste("File:", digest(x$path, serialize = FALSE, file = TRUE))
-        } else {
-          # assume form_data
+        } else if (inherits(x, "form_data")){
```
Comment (nealrichardson) [inline R/build-mock-url.R:82]:
```suggestion
        } else if (inherits(x, "form_data")) {
```

File: R/build-mock-url.R [hunk 2]
```diff
@@ -79,9 +79,11 @@ get_string_request_body <- function(req) {
...
           rawToChar(x$value)
+        } else {
+          # assume string
+          x
```
Comment (nealrichardson) [inline R/build-mock-url.R:86]: This looks generally ok, but it looks like there's [another possibility in `req_body_multipart()`](https://github.com/r-lib/httr2/blob/main/R/req-body.R#L156): `# data must be character, raw, curl::form_file, or curl::form_data`

```suggestion
        } else if (is.raw(x) {
          rawToChar(x)
        } else {
          # assume string
          x
```

**Review by nealrichardson — CHANGES_REQUESTED** [review]
Thanks for doing this.

File: R/build-mock-url.R (hunk 2 above)
Comment (jmaspons) [reply R/build-mock-url.R:86]: Is it needed to transform raw data to character? If not, I would just change the comment to: 
```suggestion
        } else {
          # assume a character string or raw
          x
```

**Comment by jmaspons** [comment]
I'm adding tests for the raw data case. For the failing R-CMD-check in windows due to #42, I would add a `skip_on_os("windows")`

File: tests/testthat/test-capture-requests.R [hunk 3]
```diff
@@ -1,6 +1,8 @@
 d <- tempfile()
 dl_file <- tempfile()
 webp_file <- tempfile()
+file_path <- tempfile()
+writeLines(letters[1:6], file_path)
```
Comment (nealrichardson) [inline tests/testthat/test-capture-requests.R:5]: The windows issue is almost surely about CRLF being inserted here. From `?writeLines`:

     Normally ‘writeLines’ is used with a text-mode connection, and the
     default separator is converted to the normal separator for that
     platform (LF on Unix/Linux, CRLF on Windows).  For more control,
     open a binary connection and specify the precise value you want
     written to the file in ‘sep’.  For even more control, use
     ‘writeChar’ on a binary connection.

I found a related test for this area in a different file, and it just uses `cat()` (with no newlines) to write to a tempfile: https://github.com/nealrichardson/httptest2/blob/main/tests/testthat/test-mock-api.R#L165

It would also be good to extend that test block ("POST with all body types") to cover the strings and raw, to make sure the request assertions work as expected.

File: R/build-mock-url.R [hunk 4]
```diff
@@ -79,9 +79,11 @@ get_string_request_body <- function(req) {
         if (inherits(x, "form_file")) {
           # hash the file contents
           paste("File:", digest(x$path, serialize = FALSE, file = TRUE))
-        } else {
-          # assume form_data
+        } else if (inherits(x, "form_data")) {
           rawToChar(x$value)
+        } else {
+          # assume character string or raw
```
Comment (nealrichardson) [inline R/build-mock-url.R:85]: I suspect we'll need to rawToChar if it is raw, given that this function says it is returning a string. But adding to the test in test-mock-api.R should confirm that one way or another.

**Review by nealrichardson — COMMENTED** [review]
Thank you for taking another pass at this. A couple of suggestions to hopefully solve the Windows issue (for this PR; we'll have to look again at #42) and finish this up.

File: R/build-mock-url.R (hunk 4 above)
Comment (jmaspons) [reply R/build-mock-url.R:85]: The new version confirms that rawToChar() is not needed

File: tests/testthat/test-capture-requests.R (hunk 3 above)
Comment (jmaspons) [reply tests/testthat/test-capture-requests.R]: Done and it solves the problem in windows

File: R/build-mock-url.R (hunk 2 above)
Comment (jmaspons) [reply R/build-mock-url.R]: Seems that rawToChar() is not needed

**Review by nealrichardson — APPROVED** [review]
Looks good, thanks for doing this!
